// variables names 
typedef struct SVarDebugInfo {
    const char *    szName; //!< name of the variable
    int             typeID; //!< var type id
} TVarDebugInfo;

// global variable holding the debug info of the variables
const TVarDebugInfo gVarDebugInfo [] = {
	{.szName="oChan4_xo", .typeID=10}, 
	{.szName="oChan4_eq", .typeID=10}, 
	{.szName="oChan4_l", .typeID=14}, 
	{.szName="oChan4_g", .typeID=1}, 
	{.szName="oChan4_d", .typeID=20}, 
	{.szName="oChan3_xo", .typeID=10}, 
	{.szName="oChan3_eq", .typeID=10}, 
	{.szName="oChan3_l", .typeID=14}, 
	{.szName="oChan3_g", .typeID=1}, 
	{.szName="oChan3_d", .typeID=20}, 
	{.szName="oChan2_xo", .typeID=10}, 
	{.szName="oChan2_eq", .typeID=10}, 
	{.szName="oChan2_l", .typeID=14}, 
	{.szName="oChan2_g", .typeID=1}, 
	{.szName="oChan2_d", .typeID=20}, 
	{.szName="oChan1_xo", .typeID=10}, 
	{.szName="oChan1_eq", .typeID=10}, 
	{.szName="oChan1_l", .typeID=14}, 
	{.szName="oChan1_g", .typeID=1}, 
	{.szName="oChan1_d", .typeID=20}, 
	{.szName="iChan1_eq", .typeID=10}, 
	{.szName="iChan1_d", .typeID=20}, 
	{.szName="iChan1_g", .typeID=1}, 
	{.szName="iChan2_eq", .typeID=10}, 
	{.szName="iChan2_d", .typeID=20}, 
	{.szName="iChan2_g", .typeID=1}, 
	{.szName="in1", .typeID=1}, 
	{.szName="in2", .typeID=1}, 
	{.szName="out", .typeID=1}, 
	{.szName="#fv_initInputChannel_ichannel_eq", .typeID=10}, 
	{.szName="#fv_initInputChannel_ichannel_d", .typeID=20}, 
	{.szName="#fv_initInputChannel_ichannel_g", .typeID=1}, 
	{.szName="#const16", .typeID=1}, 
	{.szName="#const17", .typeID=2}, 
	{.szName="#fv_initOutputChannel_ochannel_xo", .typeID=10}, 
	{.szName="#fv_initOutputChannel_ochannel_eq", .typeID=10}, 
	{.szName="#fv_initOutputChannel_ochannel_l", .typeID=14}, 
	{.szName="#fv_initOutputChannel_ochannel_g", .typeID=1}, 
	{.szName="#fv_initOutputChannel_ochannel_d", .typeID=20}, 
	{.szName="#fv_processInputChannel_y", .typeID=1}, 
	{.szName="#fv_processInputChannel_x", .typeID=1}, 
	{.szName="#fv_processInputChannel_ichannel_eq", .typeID=10}, 
	{.szName="#fv_processInputChannel_ichannel_d", .typeID=20}, 
	{.szName="#fv_processInputChannel_ichannel_g", .typeID=1}, 
	{.szName="#fv_processOutputChannel_y", .typeID=1}, 
	{.szName="#fv_processOutputChannel_x", .typeID=1}, 
	{.szName="#fv_processOutputChannel_ochannel_xo", .typeID=10}, 
	{.szName="#fv_processOutputChannel_ochannel_eq", .typeID=10}, 
	{.szName="#fv_processOutputChannel_ochannel_l", .typeID=14}, 
	{.szName="#fv_processOutputChannel_ochannel_g", .typeID=1}, 
	{.szName="#fv_processOutputChannel_ochannel_d", .typeID=20}, 
};
