// variables names 
typedef struct SVarDebugInfo {
    const char *    szName; //!< name of the variable
    int             typeID; //!< var type id
} TVarDebugInfo;

// global variable holding the debug info of the variables
const TVarDebugInfo gVarDebugInfo [] = {
	{.szName="oChan4_xo", .typeID=10}, 
	{.szName="oChan4_eq", .typeID=10}, 
	{.szName="oChan4_l", .typeID=14}, 
	{.szName="oChan4_g", .typeID=1}, 
	{.szName="oChan4_d", .typeID=20}, 
	{.szName="oChan3_xo", .typeID=10}, 
	{.szName="oChan3_eq", .typeID=10}, 
	{.szName="oChan3_l", .typeID=14}, 
	{.szName="oChan3_g", .typeID=1}, 
	{.szName="oChan3_d", .typeID=20}, 
	{.szName="oChan2_xo", .typeID=10}, 
	{.szName="oChan2_eq", .typeID=10}, 
	{.szName="oChan2_l", .typeID=14}, 
	{.szName="oChan2_g", .typeID=1}, 
	{.szName="oChan2_d", .typeID=20}, 
	{.szName="oChan1_xo", .typeID=10}, 
	{.szName="oChan1_eq", .typeID=10}, 
	{.szName="oChan1_l", .typeID=14}, 
	{.szName="oChan1_g", .typeID=1}, 
	{.szName="oChan1_d", .typeID=20}, 
	{.szName="iChan1_eq", .typeID=10}, 
	{.szName="iChan1_d", .typeID=20}, 
	{.szName="iChan1_g", .typeID=1}, 
	{.szName="iChan2_eq", .typeID=10}, 
	{.szName="iChan2_d", .typeID=20}, 
	{.szName="iChan2_g", .typeID=1}, 
	{.szName="cp_rLED", .typeID=102}, 
	{.szName="cp_lb", .typeID=101}, 
	{.szName="cp_d", .typeID=103}, 
	{.szName="cp_mb", .typeID=101}, 
	{.szName="cp_gLED", .typeID=102}, 
	{.szName="cp_p", .typeID=100}, 
	{.szName="cp_rb", .typeID=101}, 
	{.szName="sel", .typeID=2}, 
	{.szName="#const22", .typeID=2}, 
	{.szName="#const23", .typeID=2}, 
	{.szName="#const24", .typeID=2}, 
	{.szName="#const25", .typeID=3}, 
	{.szName="#fv_UIselectInputOutput_cf", .typeID=2}, 
	{.szName="#const26", .typeID=3}, 
	{.szName="#const30", .typeID=3}, 
	{.szName="#const31", .typeID=3}, 
	{.szName="#fv_UIselectChannel_cf", .typeID=2}, 
	{.szName="#const1", .typeID=3}, 
	{.szName="#const5", .typeID=3}, 
	{.szName="#fv_UIsetInpChannelValues_sel", .typeID=2}, 
	{.szName="#fv_UIsetInpChannelValues_iCh_eq", .typeID=10}, 
	{.szName="#fv_UIsetInpChannelValues_iCh_d", .typeID=20}, 
	{.szName="#fv_UIsetInpChannelValues_iCh_g", .typeID=1}, 
	{.szName="#fv_UIsetInpChannelValues_#fv_UIselectInputElement_cf", .typeID=2}, 
	{.szName="#const8", .typeID=3}, 
	{.szName="#const12", .typeID=2}, 
	{.szName="#const13", .typeID=3}, 
	{.szName="#const14", .typeID=3}, 
	{.szName="#const15", .typeID=3}, 
	{.szName="#fv_UIsetInpChannelValues_#fv_UIsetGain_valueStr", .typeID=3}, 
	{.szName="#fv_UIsetInpChannelValues_#fv_UIsetGain_displayStrBasic", .typeID=3}, 
	{.szName="#fv_UIsetInpChannelValues_#fv_UIsetGain_cf", .typeID=2}, 
	{.szName="#fv_UIsetInpChannelValues_#fv_UIsetGain_displayStr", .typeID=3}, 
	{.szName="#fv_UIsetInpChannelValues_#fv_UIsetGain_gStep", .typeID=1}, 
	{.szName="#fv_UIsetInpChannelValues_#fv_UIsetGain_gMin", .typeID=1}, 
	{.szName="#fv_UIsetInpChannelValues_#fv_UIsetGain_g", .typeID=1}, 
	{.szName="#fv_UIsetInpChannelValues_#fv_UIsetGain_gMax", .typeID=1}, 
	{.szName="#const18", .typeID=3}, 
};
