'''
Created on 29.03.2012

@author: Stefan Jaritz
'''

import csv


# ======================================
# MSO6054A
# ======================================

# reads and formats the csv data file
# generated by the Agilent Technologies
# MSO6054A oscilioscope
def MSO6054A_getData (filename):
    reader = csv.reader(open(filename, 'rb'), delimiter=',')
    i = 0
    rL = []
    for val in reader:
        if (i == 0):
            header = val
        if (i > 1) :
            rL.append((float(val[0]),float(val[1])))
        i += 1
    return (header, rL)

def MSO6054A_detectFallingAndRisingEdges (dataList):
    do = None
    i = int(0)
    L = []
    for d in dataList:
        if i != 0:
            diff = d[1] - do[1]
            if diff:
                L.append((i-1, diff))
        do = d
        i+=1
    return L

# ======================================
# Rohde&Schwarz UVP Audio Analyzer
# ======================================


def RohdeSchwarzUVPaudioAnalyzer_getData (filename):
    reader = csv.reader(open(filename, 'rb'), delimiter='\t')
    i = 0
    rL = []
    header = []
    for valR in reader:
        if (i == 15):
            header = valR; 
        if (i > 15):
            t = []
            for val in valR:
                if val == 'VOID':
                    t.append(None)
                elif val =='':
                    pass
                else:
                    t.append(float(val))
            rL.append(t)
        i += 1
    return (header, rL)

# ======================================
# gprof
# ======================================
def gprof_getData (filename):
    reader = csv.reader(open(filename, 'rb'), delimiter=' ')
    i = 0
    rL = []
    header = []
    for valR in reader:
        # remove all emty entries caused by the delimiter 
        vL = filter(None, valR)        
        if (i == 4):
            header = vL; 
        if (i > 4):
            # check if we got a call to a external function
            lenVL = len(vL)
            if lenVL == 7:
                t = (
                    float(vL[0]),
                    float(vL[1]),
                    float(vL[2]),
                    int(vL[3]),
                    float(vL[4]),
                    float(vL[5]),
                    str(vL[6])
                )
            elif lenVL == 4:
                t = (
                    float(vL[0]),
                    float(vL[1]),
                    float(vL[2]),
                    int(0),
                    float(0.0),
                    float(0.0),
                    '[ext] '+str(vL[3])
                )
            else :
                print ('error in file '+filename+' @'+str(vL))          
            rL.append(t)
        i += 1
    return (header, rL)